### ISSUE TITLE
Mid-80s LMI Lambda files useful?

### ISSUE THREAD

**Issue by dseagrav** [Interlisp/history#1]
As part of another project I dumped tapes containing two directories of Interlisp code from mid-85 or so; One source and one binary for the LMI Lambda. Is this useful?

Neither tape dumped without error but there were other unrelated files mixed in so I can't immediately tell where the errors are. The physical tapes were in very bad condition.

I can attach the files to this issue if desired or email them to someone for inspection.

I haven't tried loading any of the files, but I can give it a shot and see how badly things break.

**Comment by masinter** [comment]
I can't tell what to do without looking but I think this might be an interlisp compatibility package written for the LMI (using OLD Interlisp-D source code for some things). Do you have a LMI Lambda emulator?

If you can send me the files or a pointer to them, I'll look.

**Comment by dseagrav** [comment]
> I can't tell what to do without looking but I think this might be an interlisp compatibility package written for the LMI (using OLD Interlisp-D source code for some things). Do you have a LMI Lambda emulator?

I do have a Lambda emulator (because I wrote it).

> If you can send me the files or a pointer to them, I'll look.

I emailed them to your ACM address.

**Comment by masinter** [comment]
From a brief perusal, this looks like a (limited) Interlisp compatibility layer to aid people who wanted to port Interlisp code to LMI.

It's good to hear there's a LMI emulator in the works. You might check out
https://www.zotero.org/software-preservation/collections/GIYN9CCY

and also https://www.zotero.org/groups/2914042/interlisp/collections/38VWRV6T

**Comment by dseagrav** [comment]
Ah. Well, you have the bits, so if there's anything useful, there they are.

Thanks for the links, I'll have to check them out when I get home.
